version: "3.3"

services:
    # REDIS
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data"

    # MY_SQL
    rdb:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./rdb/conf/:/etc/mysql/conf.d:cached
            - ./rdb/data/:/var/lib/mysql:cached
        env_file: .env

    # Mongo
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        container_name: mongodb
        environment:
            - MONGODB_USER=${DB_USER}
            - MONGODB_PASS=${DB_PASSWORD}
        volumes:
            - ./mongodb/data:/data/db
        command: mongod --smallfiles

    # Dynamo
    # docker-compose [down|stop] 地点でデータが消えるので注意
    dynamo:
        image: amazon/dynamodb-local:latest
        ports:
            - "8000:8000"
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
        volumes:
            - ./dynamo/data:/data

    # DynamoDBのアドミンでの操作画面
    dynamo-admin:
        image: instructure/dynamo-local-admin:latest
        networks:
            - default
        ports:
            - 8011:8001
        depends_on:
            - "dynamo"

    # https://qiita.com/matyahiko2831/items/0b07a7577142c00d50e7
    # Elasticsserch
    elasticsearch:
        image: 'elasticsearch:6.5.0'
        ports:
            - "9200:9200"
            - "9300:9300"
        expose:
            - 9300
        volumes:
            - ./es-data/:/usr/share/elasticsearch/data
        tty: true
        environment:
            discovery.type: single-node

    elasticsearch-admin:
        image: docker.elastic.co/kibana/kibana:6.3.2
        ports:
            - "5601:5601"
        expose:
            - 5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        depends_on:
            - elasticsearch

# mongo default port :27017

